### ISSUE TITLE
Importing parallelsimulationsnode.py into another file and running it from that file

### ISSUE THREAD

**Issue by murtazabasu** [alidemir1/RosGazeboParallelSimulations#1]
Hi, your work is pretty awesome. My question is right now you are running this file and two processes get started. My question say if I wanted to import this file into another file so I will be doing it as

```
from parallelSimulationnode import Worker()
# I give these arguments
#initializing some shared values between process
global_number = mp.Value('i', 0)

# parallel training
workers = [Worker(global_number, i) for i in range(numberOfCpuCore_to_be_used)]
[w.start() for w in workers]
[w.join() for w in workers]

```
#Now instead of having a subscriber in the previous file lets say I want to pass an argument 
"msg" to the current state function inside the "run function"  

Note: I am not concerned about the subscribers and publishers here ,I just want to know how to access functions froma "multiprocessing class"

**Comment by alidemir1** [comment]
I might not understand your exact question but from what I have understood;

I think you should change 
_from parallelSimulationnode import **Worker()**_ 
with 
_from parallelSimulationnode import **Worker**_
